"""Focused unit tests for slicer discovery and command construction."""

from __future__ import annotations

import json
from collections.abc import Mapping, Sequence
from pathlib import Path

from topoforge.validation.slicers import (
    CommandExecution,
    OrcaSlicerAdapter,
    PrusaSlicerAdapter,
    SlicerAvailability,
    SlicerProfile,
    SliceStatus,
    select_slicer,
)

PRUSA_GCODE = """; generated by PrusaSlicer 2.9.6 on 2026-07-31
;LAYER_CHANGE
;LAYER_CHANGE
; filament used [mm] = 12.5
; estimated printing time (normal mode) = 2m 3s
; support_material = 0
"""

ORCA_GCODE = """; generated by OrcaSlicer 2.3.0 on 2026-07-31
; total layer number: 3
;LAYER_CHANGE
;LAYER_CHANGE
;LAYER_CHANGE
; filament used [mm] = 14.25
; estimated printing time (normal mode) = 1m 5s
; enable_support = 0
"""


class FakePrusaRunner:
    """Emit deterministic help and G-code without an external process."""

    def __init__(self, *, slice_returncode: int = 0) -> None:
        self.slice_returncode = slice_returncode
        self.calls: list[tuple[tuple[str, ...], Mapping[str, str] | None]] = []

    def __call__(
        self,
        command: Sequence[str],
        *,
        timeout_seconds: float,
        env: Mapping[str, str] | None = None,
        cwd: Path | None = None,
    ) -> CommandExecution:
        del timeout_seconds, cwd
        normalized = tuple(command)
        self.calls.append((normalized, env))
        if "--help" in normalized:
            return CommandExecution(0, "PrusaSlicer-2.9.6 based on Slic3r", "", 0.01)
        if self.slice_returncode == 0:
            output = Path(normalized[normalized.index("--output") + 1])
            output.write_text(PRUSA_GCODE, encoding="utf-8")
        return CommandExecution(self.slice_returncode, "sliced", "failure", 0.1)


class FakeOrcaRunner:
    """Emit deterministic Orca result.json and plate G-code."""

    def __init__(self) -> None:
        self.calls: list[tuple[tuple[str, ...], Mapping[str, str] | None]] = []

    def __call__(
        self,
        command: Sequence[str],
        *,
        timeout_seconds: float,
        env: Mapping[str, str] | None = None,
        cwd: Path | None = None,
    ) -> CommandExecution:
        del timeout_seconds, cwd
        normalized = tuple(command)
        self.calls.append((normalized, env))
        if "--help" in normalized:
            return CommandExecution(0, "OrcaSlicer-01.10.01.50:", "", 0.01)
        output_dir = Path(normalized[normalized.index("--outputdir") + 1])
        output_dir.joinpath("plate_1.gcode").write_text(ORCA_GCODE, encoding="utf-8")
        output_dir.joinpath("result.json").write_text(
            json.dumps(
                {
                    "error_string": "Success.",
                    "return_code": 0,
                    "sliced_plates": [{"warning_message": ""}],
                }
            ),
            encoding="utf-8",
        )
        return CommandExecution(0, "sliced", "", 0.2)


class FailedMetadataOrcaRunner(FakeOrcaRunner):
    """Write G-code but report a slicer-level failure in result.json."""

    def __call__(
        self,
        command: Sequence[str],
        *,
        timeout_seconds: float,
        env: Mapping[str, str] | None = None,
        cwd: Path | None = None,
    ) -> CommandExecution:
        execution = super().__call__(
            command,
            timeout_seconds=timeout_seconds,
            env=env,
            cwd=cwd,
        )
        normalized = tuple(command)
        if "--help" not in normalized:
            output_dir = Path(normalized[normalized.index("--outputdir") + 1])
            output_dir.joinpath("result.json").write_text(
                json.dumps({"error_string": "Invalid printer profile", "return_code": 0}),
                encoding="utf-8",
            )
        return execution


class FallbackRunner:
    """Fail Orca probing while allowing PrusaSlicer probing."""

    def __call__(
        self,
        command: Sequence[str],
        *,
        timeout_seconds: float,
        env: Mapping[str, str] | None = None,
        cwd: Path | None = None,
    ) -> CommandExecution:
        del timeout_seconds, env, cwd
        if "orca" in Path(command[0]).name.casefold():
            return CommandExecution(1, "", "GLIBC_2.38 not found", 0.01)
        return CommandExecution(0, "PrusaSlicer-2.9.6 based on Slic3r", "", 0.01)


def _executable(path: Path, name: str) -> Path:
    executable = path / name
    executable.write_text("#!/bin/sh\n", encoding="utf-8")
    executable.chmod(0o755)
    return executable


def test_prusa_invocation_has_explicit_output_and_profile(tmp_path: Path) -> None:
    runner = FakePrusaRunner()
    executable = _executable(tmp_path, "prusa-slicer")
    model = tmp_path / "terrain.stl"
    model.write_text("solid terrain\nendsolid terrain\n", encoding="ascii")
    profile_path = tmp_path / "printer.ini"
    profile_path.write_text("layer_height = 0.2\n", encoding="ascii")
    output = tmp_path / "nested" / "terrain.gcode"
    adapter = PrusaSlicerAdapter(executable, runner=runner)

    result = adapter.slice(
        model,
        output,
        profile=SlicerProfile(name="test-printer", settings=(profile_path,)),
        extra_args=("--fill-density", "15%"),
    )

    assert result.status is SliceStatus.SUCCEEDED
    assert result.slicer.version == "2.9.6"
    assert result.profile == "test-printer"
    assert result.gcode_generated is True
    assert result.metrics.layer_count == 2
    assert output.read_text(encoding="utf-8") == PRUSA_GCODE
    slice_command = runner.calls[-1][0]
    assert "--export-gcode" in slice_command
    assert "--output" in slice_command
    assert "--load" in slice_command
    assert str(output) not in slice_command
    assert Path(slice_command[slice_command.index("--output") + 1]).parent == output.parent


def test_prusa_failed_process_does_not_publish_gcode(tmp_path: Path) -> None:
    runner = FakePrusaRunner(slice_returncode=2)
    executable = _executable(tmp_path, "prusa-slicer")
    model = tmp_path / "terrain.stl"
    model.write_text("solid terrain\nendsolid terrain\n", encoding="ascii")
    output = tmp_path / "terrain.gcode"

    result = PrusaSlicerAdapter(executable, runner=runner).slice(model, output)

    assert result.status is SliceStatus.FAILED
    assert result.exit_code == 2
    assert result.gcode_generated is False
    assert not output.exists()


def test_missing_executable_returns_unavailable_result(tmp_path: Path) -> None:
    model = tmp_path / "terrain.stl"
    model.write_text("solid terrain\nendsolid terrain\n", encoding="ascii")
    adapter = PrusaSlicerAdapter(tmp_path / "missing-prusa-slicer")

    info = adapter.probe()
    result = adapter.slice(model, tmp_path / "terrain.gcode")

    assert info.status is SlicerAvailability.UNAVAILABLE
    assert result.status is SliceStatus.UNAVAILABLE
    assert result.exit_code is None
    assert "does not identify an executable" in (result.error or "")


def test_selection_falls_back_when_orca_binary_cannot_start(tmp_path: Path) -> None:
    orca = _executable(tmp_path, "orca-slicer")
    prusa = _executable(tmp_path, "prusa-slicer")

    selected = select_slicer(
        orca_executable=orca,
        prusa_executable=prusa,
        runner=FallbackRunner(),
    )

    assert selected.name == "PrusaSlicer"
    assert selected.probe().status is SlicerAvailability.AVAILABLE


def test_orca_result_json_failure_does_not_publish_gcode(tmp_path: Path) -> None:
    executable = _executable(tmp_path, "orca-slicer")
    model = tmp_path / "terrain.stl"
    model.write_text("solid terrain\nendsolid terrain\n", encoding="ascii")
    output = tmp_path / "terrain.gcode"

    result = OrcaSlicerAdapter(executable, runner=FailedMetadataOrcaRunner()).slice(model, output)

    assert result.status is SliceStatus.FAILED
    assert result.error == "Invalid printer profile"
    assert result.gcode_generated is False
    assert not output.exists()


def test_orca_uses_profile_groups_and_moves_plate_to_exact_output(tmp_path: Path) -> None:
    runner = FakeOrcaRunner()
    executable = _executable(tmp_path, "OrcaSlicer_Linux_AppImage_V2.3.0.AppImage")
    model = tmp_path / "terrain.stl"
    model.write_text("solid terrain\nendsolid terrain\n", encoding="ascii")
    process = tmp_path / "process.json"
    machine = tmp_path / "machine.json"
    filament = tmp_path / "filament.json"
    for profile_path in (process, machine, filament):
        profile_path.write_text("{}", encoding="utf-8")
    output = tmp_path / "terrain-explicit.gcode"
    adapter = OrcaSlicerAdapter(executable, runner=runner)

    result = adapter.slice(
        model,
        output,
        profile=SlicerProfile(
            name="MK3S PLA",
            settings=(process, machine),
            filaments=(filament,),
        ),
    )

    assert result.status is SliceStatus.SUCCEEDED
    assert result.slicer.version == "2.3.0"
    assert result.output_gcode == output.resolve()
    assert output.read_text(encoding="utf-8") == ORCA_GCODE
    assert result.metrics.layer_count == 3
    slice_command, environment = runner.calls[-1]
    assert slice_command[slice_command.index("--load-settings") + 1] == (
        f"{process.resolve()};{machine.resolve()}"
    )
    assert slice_command[slice_command.index("--load-filaments") + 1] == str(filament.resolve())
    assert "--slice" in slice_command
    assert "--outputdir" in slice_command
    assert environment is not None
    assert environment["APPIMAGE_EXTRACT_AND_RUN"] == "1"
