"""Metric parsing tests shared by slicer adapters."""

from topoforge.validation.slicers import parse_gcode_generator, parse_gcode_metrics


def test_parse_orca_metrics_and_diagnostics() -> None:
    gcode = """; generated by OrcaSlicer 2.3.0 on 2026-07-31
; total layer number: 100
;LAYER_CHANGE
; filament used [mm] = 1360.94
; filament used [cm3] = 3.27
; total filament used [g] = 4.08
; total layers count = 100
; estimated printing time (normal mode) = 1h 20m 2s
; enable_support = 0
"""
    diagnostics = "WARNING: Empty layer between 1.0 and 1.2.\nFloating region detected."

    metrics = parse_gcode_metrics(gcode, diagnostics)

    assert parse_gcode_generator(gcode) == ("OrcaSlicer", "2.3.0")
    assert metrics.estimated_time_seconds == 4802
    assert metrics.filament_used_mm == 1360.94
    assert metrics.filament_used_cm3 == 3.27
    assert metrics.filament_used_g == 4.08
    assert metrics.layer_count == 100
    assert metrics.support_material is False
    assert metrics.empty_layer_warning is True
    assert metrics.floating_region_warning is True
    assert metrics.warnings


def test_parse_prusa_metrics_with_layer_fallback_and_support_paths() -> None:
    gcode = """; generated by PrusaSlicer 2.9.6 on 2026-07-31
;LAYER_CHANGE
;LAYER_CHANGE
;LAYER_CHANGE
;TYPE:Support material
; filament used [mm] = 42.5
; estimated printing time (normal mode) = 17m 49s
; support_material = 1
"""

    metrics = parse_gcode_metrics(gcode)

    assert metrics.estimated_time_seconds == 1069
    assert metrics.layer_count == 3
    assert metrics.support_material is True


def test_out_of_bed_detection_uses_diagnostics_not_start_gcode_comments() -> None:
    gcode = "; generated by OrcaSlicer 2.3.0\nG1 Y-3 ; go outside print area\n"

    normal = parse_gcode_metrics(gcode)
    failed = parse_gcode_metrics(gcode, "An object outside the print area was detected.")

    assert normal.out_of_bed is False
    assert failed.out_of_bed is True
