from __future__ import annotations

import json
from collections.abc import Sequence
from pathlib import Path

from typer.testing import CliRunner

from topoforge.cli.app import app
from topoforge.config import dump_resolved_config
from topoforge.models import BuildConfig, SamplingMode
from topoforge.raster import SyntheticTerrain, create_synthetic_geotiff
from topoforge.validation.slicers import (
    SlicerAvailability,
    SliceResult,
    SlicerInfo,
    SlicerProfile,
    SliceStatus,
    parse_gcode_metrics,
)
from topoforge.workflow import (
    LocalWorkflowConfig,
    LocalWorkflowManifest,
    LocalWorkflowStatus,
    WorkflowStage,
    WorkflowState,
    run_local_workflow,
)

runner = CliRunner()


class RecoveringFakeSlicer:
    def __init__(self, executable: Path) -> None:
        self.executable = executable
        self.fail_next = True
        executable.write_text("stable fake slicer executable\n", encoding="utf-8")

    @property
    def name(self) -> str:
        return "PrusaSlicer"

    def probe(self, *, refresh: bool = False) -> SlicerInfo:
        del refresh
        return SlicerInfo(
            name=self.name,
            version="2.9.6",
            executable=self.executable,
            status=SlicerAvailability.AVAILABLE,
        )

    def slice(
        self,
        input_model: Path,
        output_gcode: Path,
        *,
        profile: SlicerProfile | None = None,
        extra_args: Sequence[str] = (),
        timeout_seconds: float = 600.0,
    ) -> SliceResult:
        del extra_args, timeout_seconds
        if self.fail_next:
            self.fail_next = False
            return SliceResult(
                status=SliceStatus.FAILED,
                slicer=self.probe(),
                profile=(profile or SlicerProfile()).label,
                input_model=input_model,
                output_gcode=output_gcode,
                command=(str(self.executable), "--export-gcode", str(input_model)),
                exit_code=1,
                duration_seconds=0.1,
                error="synthetic interruption",
            )
        output_gcode.parent.mkdir(parents=True, exist_ok=True)
        gcode = """; generated by PrusaSlicer 2.9.6
; estimated printing time (normal mode) = 1m 2s
; filament used [mm] = 12.0
; filament used [cm3] = 0.03
; filament used [g] = 0.04
; total layers count = 7
; support_material = 0
G28
G1 X1 Y1 Z0.2
"""
        output_gcode.write_text(gcode, encoding="utf-8")
        return SliceResult(
            status=SliceStatus.SUCCEEDED,
            slicer=self.probe(),
            profile=(profile or SlicerProfile()).label,
            input_model=input_model,
            output_gcode=output_gcode,
            command=(str(self.executable), "--export-gcode", str(input_model)),
            exit_code=0,
            duration_seconds=0.1,
            stdout="synthetic slice succeeded",
            gcode_generated=True,
            gcode_size_bytes=output_gcode.stat().st_size,
            metrics=parse_gcode_metrics(gcode),
        )


def test_local_run_resumes_after_slice_failure_and_reuses_verified_stages(
    tmp_path: Path,
) -> None:
    source = create_synthetic_geotiff(
        tmp_path / "source.tif",
        SyntheticTerrain.SADDLE,
        rows=16,
        columns=20,
        pixel_size_m=20.0,
    )
    workspace = tmp_path / "workflow"
    build = BuildConfig(
        dem_path=source,
        output_dir=workspace,
        model_width_mm=90.0,
        max_height_mm=30.0,
        sampling_mode=SamplingMode.SOURCE_PRESERVING,
        max_grid_cells=20_000,
    )
    config_path = tmp_path / "build.yaml"
    dump_resolved_config(build, config_path)
    arguments = [
        "run",
        "--config",
        str(config_path),
        "--max-tile-size-mm",
        "50",
        "40",
        "--no-slice",
    ]

    first = runner.invoke(app, arguments)
    assert first.exit_code == 0, first.output
    first_payload = json.loads(first.output)
    assert first_payload["completed_stages"] == [
        "source",
        "build",
        "layout",
        "extract",
        "mesh",
        "connect",
    ]
    assert first_payload["reused_stages"] == []
    manifest_path = workspace / "workflow-manifest.json"
    non_slice_manifest = LocalWorkflowManifest.model_validate_json(
        manifest_path.read_text(encoding="utf-8")
    )
    assert non_slice_manifest.final_stage is WorkflowStage.CONNECT
    assert non_slice_manifest.required_checks_passed is True

    repeat = runner.invoke(app, arguments)
    assert repeat.exit_code == 0, repeat.output
    repeat_payload = json.loads(repeat.output)
    assert repeat_payload["completed_stages"] == []
    assert repeat_payload["reused_stages"] == [
        "source",
        "build",
        "layout",
        "extract",
        "mesh",
        "connect",
    ]

    workflow = LocalWorkflowConfig(
        workspace_dir=workspace,
        build=build,
        maximum_tile_width_mm=50.0,
        maximum_tile_depth_mm=40.0,
        overlap_cells=1,
        slicing_enabled=True,
    )
    slicer = RecoveringFakeSlicer(tmp_path / "fake-prusa-slicer")

    try:
        run_local_workflow(workflow, adapter=slicer)
    except Exception as exc:
        assert "synthetic interruption" in str(exc)
    else:
        raise AssertionError("recovering fake slicer should fail its first invocation")
    failed_status = LocalWorkflowStatus.model_validate_json(
        (workspace / "workflow-status.json").read_text(encoding="utf-8")
    )
    assert failed_status.state is WorkflowState.FAILED
    assert failed_status.current_stage is WorkflowStage.SLICE
    assert failed_status.ready_stages == (
        WorkflowStage.SOURCE,
        WorkflowStage.BUILD,
        WorkflowStage.LAYOUT,
        WorkflowStage.EXTRACT,
        WorkflowStage.MESH,
        WorkflowStage.CONNECT,
    )
    assert failed_status.failure_path is not None
    assert (workspace / failed_status.failure_path).is_file()

    recovered = run_local_workflow(workflow, adapter=slicer)
    assert recovered.completed_stages == (WorkflowStage.SLICE,)
    assert recovered.reused_stages == (
        WorkflowStage.SOURCE,
        WorkflowStage.BUILD,
        WorkflowStage.LAYOUT,
        WorkflowStage.EXTRACT,
        WorkflowStage.MESH,
        WorkflowStage.CONNECT,
    )
    recovered_bytes = manifest_path.read_bytes()
    recovered_manifest = LocalWorkflowManifest.model_validate_json(recovered_bytes.decode("utf-8"))
    assert recovered_manifest.final_stage is WorkflowStage.SLICE
    assert recovered_manifest.required_checks_passed is True
    slice_output = recovered.stage_outputs[WorkflowStage.SLICE]
    assert (slice_output / "tile-slice-manifest.json").is_file()

    reused = run_local_workflow(workflow, adapter=slicer)
    assert reused.completed_stages == ()
    expected_stages = tuple(stage for stage in WorkflowStage if stage is not WorkflowStage.PROJECT)
    assert reused.reused_stages == expected_stages
    assert manifest_path.read_bytes() == recovered_bytes
    final_status = LocalWorkflowStatus.model_validate_json(
        (workspace / "workflow-status.json").read_text(encoding="utf-8")
    )
    assert final_status.state is WorkflowState.COMPLETED
    assert final_status.current_stage is None
    assert final_status.ready_stages == expected_stages


def test_project_evidence_requires_slicing_and_official_bambu(tmp_path: Path) -> None:
    source = tmp_path / "source.tif"
    source.write_bytes(b"identity-only test source")
    build = BuildConfig(
        dem_path=source,
        output_dir=tmp_path / "workflow",
        model_width_mm=40.0,
        max_height_mm=20.0,
    )

    try:
        LocalWorkflowConfig(
            workspace_dir=tmp_path / "workflow",
            build=build,
            slicing_enabled=False,
            project_evidence_enabled=True,
        )
    except ValueError as exc:
        assert "requires slicing_enabled" in str(exc)
    else:
        raise AssertionError("project evidence without slicing must be rejected")

    slicer = RecoveringFakeSlicer(tmp_path / "fake-prusa-project-slicer")
    slicer.fail_next = False
    workflow = LocalWorkflowConfig(
        workspace_dir=tmp_path / "workflow",
        build=build,
        slicing_enabled=True,
        project_evidence_enabled=True,
    )
    try:
        run_local_workflow(workflow, adapter=slicer)
    except Exception as exc:
        assert "requires the official Bambu Studio" in str(exc)
    else:
        raise AssertionError("project evidence with a diagnostic slicer must be rejected")
    assert not workflow.workspace_dir.exists()
