from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

import pytest
import rasterio

from topoforge.engine import build_local_terrain
from topoforge.exceptions import ConfigurationError, SlicerError
from topoforge.models import BuildConfig, SamplingMode
from topoforge.raster import SyntheticTerrain, create_synthetic_geotiff
from topoforge.tiling import (
    TileLayoutConfig,
    extract_tile_set,
    generate_print_tile_set,
    generate_tile_mesh_set,
    plan_tile_layout,
    slice_print_tile_set,
    verify_tile_slice_set,
    write_tile_layout,
)
from topoforge.validation.slicers import (
    SlicerAvailability,
    SliceResult,
    SlicerInfo,
    SlicerProfile,
    SliceStatus,
    parse_gcode_metrics,
)


class FakeTileSlicer:
    def __init__(self, executable: Path, *, support_material: bool = False) -> None:
        self.executable = executable
        self.support_material = support_material
        executable.write_text("fake slicer executable\n", encoding="utf-8")

    @property
    def name(self) -> str:
        return "PrusaSlicer"

    def probe(self, *, refresh: bool = False) -> SlicerInfo:
        del refresh
        return SlicerInfo(
            name=self.name,
            version="2.9.6",
            executable=self.executable,
            status=SlicerAvailability.AVAILABLE,
        )

    def slice(
        self,
        input_model: Path,
        output_gcode: Path,
        *,
        profile: SlicerProfile | None = None,
        extra_args: Sequence[str] = (),
        timeout_seconds: float = 600.0,
    ) -> SliceResult:
        del extra_args, timeout_seconds
        output_gcode.parent.mkdir(parents=True, exist_ok=True)
        support = "1" if self.support_material else "0"
        gcode = f"""; generated by PrusaSlicer 2.9.6
; estimated printing time (normal mode) = 1h 2m 3s
; filament used [mm] = 100.0
; filament used [cm3] = 0.25
; filament used [g] = 0.31
; total layers count = 42
; support_material = {support}
G28
G1 X1 Y1 Z0.2
"""
        output_gcode.write_text(gcode, encoding="utf-8")
        metrics = parse_gcode_metrics(gcode)
        return SliceResult(
            status=SliceStatus.SUCCEEDED,
            slicer=self.probe(),
            profile=(profile or SlicerProfile()).label,
            input_model=input_model,
            output_gcode=output_gcode,
            command=(str(self.executable), "--export-gcode", str(input_model)),
            exit_code=0,
            duration_seconds=0.25,
            stdout="fake slice succeeded",
            stderr="",
            gcode_generated=True,
            gcode_size_bytes=output_gcode.stat().st_size,
            metrics=metrics,
        )


def _print_set(tmp_path: Path) -> tuple[Path, Path, Path, Path]:
    source = create_synthetic_geotiff(
        tmp_path / "source.tif",
        SyntheticTerrain.SADDLE,
        rows=16,
        columns=20,
        pixel_size_m=20.0,
    )
    bundle = tmp_path / "bundle"
    result = build_local_terrain(
        BuildConfig(
            dem_path=source,
            output_dir=bundle,
            model_width_mm=90.0,
            max_height_mm=30.0,
            sampling_mode=SamplingMode.SOURCE_PRESERVING,
            max_grid_cells=20_000,
        )
    )
    with rasterio.open(result.artifacts["processed_dem"]) as dataset:
        shape = dataset.shape
    dimensions = result.validation["dimensions_mm"]
    layout = plan_tile_layout(
        TileLayoutConfig(
            source_grid_shape=shape,
            model_width_mm=float(dimensions[0]),
            model_depth_mm=float(dimensions[1]),
            maximum_tile_width_mm=50.0,
            maximum_tile_depth_mm=40.0,
            overlap_cells=1,
        )
    )
    layout_path = write_tile_layout(layout, tmp_path / "tile-layout.json")
    tile_set = extract_tile_set(bundle, layout_path, tmp_path / "tile-set").output_dir
    mesh_set = generate_tile_mesh_set(tile_set, bundle, tmp_path / "mesh-set").output_dir
    print_set = generate_print_tile_set(
        mesh_set, tile_set, bundle, tmp_path / "print-set"
    ).output_dir
    return bundle, tile_set, mesh_set, print_set


def test_every_print_local_tile_is_actually_sliced_and_reopened(tmp_path: Path) -> None:
    bundle, tile_set, mesh_set, print_set = _print_set(tmp_path)
    machine = tmp_path / "machine.json"
    process = tmp_path / "process.json"
    filament = tmp_path / "filament.json"
    machine.write_text('{"machine":"test"}\n', encoding="utf-8")
    process.write_text('{"process":"test"}\n', encoding="utf-8")
    filament.write_text('{"filament":"test"}\n', encoding="utf-8")
    profile = SlicerProfile(
        name="test profile",
        settings=(machine, process),
        filaments=(filament,),
    )
    adapter = FakeTileSlicer(tmp_path / "fake-prusa-slicer")

    result = slice_print_tile_set(
        print_set,
        mesh_set,
        tile_set,
        bundle,
        tmp_path / "slice-set",
        adapter=adapter,
        profile=profile,
    )
    evidence = verify_tile_slice_set(result.output_dir, print_set, mesh_set, tile_set, bundle)

    assert evidence["tile_grid_shape"] == (2, 2)
    assert evidence["tile_count"] == 4
    assert evidence["slicer"]["name"] == "PrusaSlicer"
    assert evidence["profile"] == "test profile"
    assert evidence["total_estimated_time_seconds"] == 4 * 3723
    assert evidence["total_filament_used_mm"] == pytest.approx(400.0)
    assert evidence["total_filament_used_cm3"] == pytest.approx(1.0)
    assert evidence["total_filament_used_g"] == pytest.approx(1.24)
    assert evidence["maximum_layer_count"] == 42
    assert evidence["all_exit_codes_zero"] is True
    assert evidence["no_out_of_bed"] is True
    assert evidence["no_empty_layers"] is True
    assert evidence["no_floating_regions"] is True
    assert evidence["no_support_material"] is True
    assert evidence["required_checks_passed"] is True
    assert len(result.gcode_paths) == 4
    assert len(result.report_paths) == 4
    assert all(path.is_file() and path.stat().st_size > 0 for path in result.gcode_paths)
    assert sorted(path.name for path in (result.output_dir / "profiles").iterdir()) == [
        "filament-00-filament.json",
        "settings-00-machine.json",
        "settings-01-process.json",
    ]

    tampered = result.gcode_paths[0]
    tampered.write_text(tampered.read_text(encoding="utf-8") + "; tampered\n", encoding="utf-8")
    with pytest.raises(ConfigurationError, match="G-code checksum mismatch"):
        verify_tile_slice_set(result.output_dir, print_set, mesh_set, tile_set, bundle)


def test_tile_slice_rejects_support_material_and_cleans_partial_output(tmp_path: Path) -> None:
    bundle, tile_set, mesh_set, print_set = _print_set(tmp_path)
    output = tmp_path / "slice-failed"
    adapter = FakeTileSlicer(tmp_path / "fake-support-slicer", support_material=True)

    with pytest.raises(SlicerError, match="quality gate failed"):
        slice_print_tile_set(
            print_set,
            mesh_set,
            tile_set,
            bundle,
            output,
            adapter=adapter,
        )
    assert not output.exists()
    assert not list(tmp_path.glob(".slice-failed.topoforge-stage-*"))
