import { expect, test } from "@playwright/test";

test("drafts, model presets and workspace panels survive normal use", async ({ page }, testInfo) => {
  test.slow();
  const errors: string[] = [];
  const jobSubmissions: string[] = [];
  page.on("pageerror", error => errors.push(String(error)));
  page.on("request", request => {
    if (request.method() === "POST" && request.url().endsWith("/api/v1/jobs")) jobSubmissions.push(request.url());
  });
  await page.addInitScript(() => {
    localStorage.setItem("topoforge-language", "zh-CN");
    localStorage.setItem("topoforge-basemap-mode", "off");
  });
  await page.goto("/");
  const width = page.getByRole("spinbutton", { name: "宽度（毫米）", exact: true });
  await width.fill("120");
  await page.getByRole("button", { name: "高级", exact: true }).click();
  await page.getByRole("combobox", { name: "连接器总间隙（毫米）" }).selectOption("0.3");
  await page.getByRole("button", { name: "基础", exact: true }).click();
  await expect(page.getByText("已调整高级设置，生成时仍会使用")).toBeVisible();
  await page.locator("summary").filter({ hasText: "常用预设" }).click();
  await page.getByRole("textbox", { name: "预设名称", exact: true }).fill("桌面模型");
  await page.getByRole("button", { name: "保存当前模型设置", exact: true }).click();
  await expect(page.getByText("预设已保存", { exact: true })).toBeVisible();
  await width.fill("200");
  await page.getByRole("textbox", { name: "工作区名称", exact: true }).fill("saved-ui-draft");
  await page.getByRole("button", { name: "边界框", exact: true }).click();
  await page.getByRole("button", { name: "应用预设", exact: true }).click();
  await expect(width).toHaveValue("120");
  await expect(page.getByRole("button", { name: "边界框", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("textbox", { name: "工作区名称", exact: true })).toHaveValue("saved-ui-draft");
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem("topoforge-form-draft-v1")!).value.modelWidthMm)).toBe(120);
  await page.reload();
  await expect(page.getByText("已恢复上次的草稿")).toBeVisible();
  await expect(width).toHaveValue("120");
  await expect(page.getByRole("button", { name: "边界框", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "查看高级设置 →", exact: true }).click();
  await expect(page.getByRole("combobox", { name: "连接器总间隙（毫米）" })).toHaveValue("0.3");
  await page.getByRole("button", { name: "基础", exact: true }).click();
  const map = page.locator(".maplibregl-map");
  const initialWidth = await map.evaluate(element => element.clientWidth);
  await page.getByRole("button", { name: "收起模型设置", exact: true }).click();
  await expect(width).toBeHidden();
  if (testInfo.project.name === "desktop") await expect.poll(() => map.evaluate(element => element.clientWidth)).toBeGreaterThan(initialWidth + 200);
  await expect.poll(() => page.locator(".maplibregl-canvas").evaluate((canvas: HTMLCanvasElement) => Math.abs(canvas.clientWidth - canvas.closest(".maplibregl-map")!.clientWidth))).toBeLessThanOrEqual(1);
  await page.getByRole("button", { name: "展开模型设置", exact: true }).click();
  await expect(width).toHaveValue("120");
  await page.getByRole("button", { name: "收起任务与结果", exact: true }).click();
  await expect(page.locator(".results-panel")).toBeHidden();
  await page.getByRole("button", { name: "展开任务与结果", exact: true }).click();
  await expect(page.locator(".results-panel")).toBeVisible();
  await page.getByRole("button", { name: "EN", exact: true }).click();
  await expect(page.getByRole("button", { name: "Basic", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("button", { name: "Start build", exact: true })).toBeEnabled();
  const dimensions = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, client: document.documentElement.clientWidth }));
  expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.client + 1);
  await page.screenshot({ path: testInfo.outputPath("workspace-settings.png"), fullPage: true });
  expect(jobSubmissions).toEqual([]);
  expect(errors).toEqual([]);
});
